export const ADD_TO_TROLLEY = "ADD_TO_TROLLEY";
export const REMOVE_FROM_TROLLEY = "REMOVE_FROM_t=TROLLEY";
export const INCREASE_NUM_OF_PRODUCTS = "INCREASE_NUM_OF_PRODUCTS";
export const DECREASE_NUM_OF_PRODUCTS = "DECREASE_NUM_OF_PRODUCTS";
